name: NusaRPG
version: '1.0.0'
main: com.github.cahyunkk.nusarpg.NusaRPG
api-version: '1.21'
softdepend: [NusaItems, NusaMobs, NusaSkills]
description: Plugin RPG server — class/job, stats pemain, level, skill tree, integrasi NusaItems & NusaSkills.
website: https://github.com/cahyunkk/plugin-slimefun

commands:
  nusa:
    description: RPG main command
    aliases: [rpg]
permissions:
  nusarpg.admin:
    default: op
  nusarpg.use:
    default: true
