name: NusaEngine
version: '1.0.0'
main: com.github.cahyunkk.nusaengine.NusaEngine
api-version: '1.21'
softdepend: [NusaMobs, NusaItems]
description: Engine framework untuk NusaMobs — stats, AI behavior, dan model renderer support.
website: https://github.com/cahyunkk/plugin-slimefun

commands:
  nusaengine:
    description: Engine control
permissions:
  nusaengine.admin:
    default: op
